DO ' BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = ''booking_status'') THEN
        CREATE TYPE booking_status AS ENUM (''WAITING'', ''APPROVED'', ''REJECTED'', ''CANCELLED'');
    END IF;
END ';

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description VARCHAR(512) NOT NULL,
    requestor_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT pk_request PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    is_available INT NOT NULL,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    request_id BIGINT REFERENCES requests(id),
    CONSTRAINT pk_item PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    booker_id BIGINT REFERENCES users(id),
    item_id BIGINT REFERENCES items(id),
    status booking_status,
    CONSTRAINT pk_booking PRIMARY KEY (id)
    );